	{include
  	file="layout/head.tpl"
  	language=$language
  }
  
  <body>

  	{include
  		file="layout/header.tpl"
	  	language=$language
      userid=$userid
      current_version=$current_version
      base_url=$base_url
  	}

    <div class="container-fluid" id="main-content">
      <div class="row-fluid">
        <div class="span12">
         	<div class="annotator-container" id="help-content">
          	<div class="headline">Annotation tool help</div>
            <div>
      
              <div class="span3 bs-docs-sidebar">
                <ul class="nav nav-tabs nav-stacked" id="help-nav-menu">
                  <li><a href="#"><i class="icon-chevron-right"></i>Topics</a></li>
                  <li><a href="#open-video"><i class="icon-chevron-right"></i>Open Video</a></li>
                  <li><a href="#create-annotation"><i class="icon-chevron-right"></i>Create an annotation</a></li>
                  <li><a href="#edit-annotation"><i class="icon-chevron-right"></i>Edit an annotation</a></li>
                  <li><a href="#delete-annotation"><i class="icon-chevron-right"></i>Delete annotations</a></li>
                  <li><a href="#save-annotation"><i class="icon-chevron-right"></i>Save annotations</a></li>
                  <li><a href="#additional"><i class="icon-chevron-right"></i>Additional info</a></li>
                </ul>
              </div>
              
              <div data-spy="scroll" data-target="#help-nav-menu" data-offset="0">
              
                <!-- Open video -->
                <div class="span9">
                  <section id="open-video">
                    <div class="page-header">
                      <h1>Open video</h1>
                    </div>
                    <p class="lead">Explains how to load a video in the annotation tool and how to make new HTML5 videos available for the annotation tool.</p>
          
                    <div class="row-fluid">
                      <h2>Screencast</h2>
                      <object width="790" height="410"><param name="movie" value="https://www.youtube-nocookie.com/v/3_uYE21iq0E?version=3&amp;hl=de_DE&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://www.youtube-nocookie.com/v/3_uYE21iq0E?version=3&amp;hl=de_DE&amp;rel=0" type="application/x-shockwave-flash" width="790" height="410" allowscriptaccess="always" allowfullscreen="true"></embed></object>
                      <h2>Detailed description</h2>
                      <p>The loading screen allows selecting between annotated videos and non-annotated videos which are available in the specified CMF (Connected Media Framework) instance. Furthermore, you can also add any existing HTML5 video to the CMF by using the video input field.</p>
                      <p>When you are loading an annotated video, every existing annotation gets loaded automatically in the annotation tool and will be available in the timeline. This allows editing annotations, deleting them and adding new ones.<br />Every other video without annotations will show you an autogenerated demo annotation when loaded.</p>
                      <p>The option "Specify video url" allows adding HTML5 videos to the CMF and annotating them. It is important that the video URL is reachable online, otherwise the video can't get added.<br />The annotation tool will show the timeline with the first demo annotation as soon as the video has been added to the CMF and is loaded in the annotation tool properly.</p>
                      <p>If you want to use a different CMF instance you have to contact your local administrator.</p>
                    </div>
                  </section>
                </div>
                
                <div class="span9">
                  <section id="create-annotation">
                    <div class="page-header">
                      <h1>Create an annotation</h1>
                    </div>
                    <p class="lead">Explains how to add new annotations in the annotation tool.</p>
          
                    <div class="row-fluid">
                      <h2>Screencast</h2>
                      <object width="790" height="410"><param name="movie" value="https://www.youtube-nocookie.com/v/c_9XxW-RpUA?version=3&amp;hl=de_DE&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://www.youtube-nocookie.com/v/c_9XxW-RpUA?version=3&amp;hl=de_DE&amp;rel=0" type="application/x-shockwave-flash" width="790" height="410" allowscriptaccess="always" allowfullscreen="true"></embed></object>
                      <h2>Detailed description</h2>
                      <p>Annotations allow you to enrich your selected video with more information. If you are watching a video which shows e.g. the city of Vienna you could enrich it by creating an annotation about Vienna. This can be a map of the city, textal information which describes Vienna, an external video, a web site, ... and many more.</p>
                      <p>There are several possibilities to add a new annotation to the timeline. You can either click on the "add" button to create a new annotation or simply perform a double-click in the timeline.</p>
                      <p>The annotation tool automatically creates a popup widget which allows you searching or linking external sources to it. You can decide between:</p>
                      <ul>
                      	<li>Search for any string in DbPedia (similar to Wikipedia)</li>
                        <li>Search for a map in Geonames</li>
                        <li>Attach any HTML web source</li>
                      </ul>
                      <p>You can browse through search results or select your attached HTML source and optinally you are allowed to override the found title. If you selected a HTML web source you should specify a title, otherwise the URL is used as title.</p>
                      <p>Finally, you can select how the annotation shall get represended and finish by clicking on continue.</p>
                      <p>The annotation can get dragged in the timeline to specify its start and end time. Furthermore, its length can also get changed (which represents the time it is shown in the player).</p>
                      <p>If you want to link a spatial region in the video to the annotation, you can simply select it by clicking in the video and selecting an area.<br />
                      Note: You have to select an annotation before you can add/edit a spatial region</p>
                    </div>
                  </section>
                </div>
                
                <div class="span9">
                  <section id="edit-annotation">
                    <div class="page-header">
                      <h1>Edit an annotation</h1>
                    </div>
                    <p class="lead">Explains how to edit existing in the annotation tool.</p>
          
                    <div class="row-fluid">
                      <h2>Screencast</h2>
                      <object width="790" height="410"><param name="movie" value="https://www.youtube-nocookie.com/v/4FeBTDi0BnY?version=3&amp;hl=de_DE&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://www.youtube-nocookie.com/v/4FeBTDi0BnY?version=3&amp;hl=de_DE&amp;rel=0" type="application/x-shockwave-flash" width="790" height="410" allowscriptaccess="always" allowfullscreen="true"></embed></object>
                      <h2>Detailed description</h2>
                      <p>Select an existing annotation in the timeline by clicking on it and two icons will appear at the right of it.</p>
                      <p>If you want to edit the linked content of the annotation you have to click on the pencil icon.</p>
                      <p>If you want to change its display time or time point, move the annotation in the timeline or enlarge/shorten it.</p>
                      <p>If you want to modify/add a spatial region, select it within the video area and adapt it to your needs.</p>
                    </div>
                  </section>
                </div>
                
                <div class="span9">
                  <section id="delete-annotation">
                    <div class="page-header">
                      <h1>Delete annotations</h1>
                    </div>
                    <p class="lead">Explains how to delete existing annotations from the annotation tool.</p>
          
                    <div class="row-fluid">
                      <h2>Screencast</h2>
                      <object width="790" height="410"><param name="movie" value="https://www.youtube-nocookie.com/v/Amiso3-RMO8?hl=de_DE&amp;version=3&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://www.youtube-nocookie.com/v/Amiso3-RMO8?hl=de_DE&amp;version=3&amp;rel=0" type="application/x-shockwave-flash" width="790" height="410" allowscriptaccess="always" allowfullscreen="true"></embed></object>
                      <h2>Detailed description</h2>
                      <p>Select an existing annotation in the timeline by clicking on it and two icons will appear at the right of it.</p>
                      <p>Click on the red x to delete the selected annotation.<br />
                      <strong>Important:</strong> Be careful because you can't undo this operation!</p>
                    </div>
                  </section>
                </div>
                
                <div class="span9">
                  <section id="save-annotation">
                    <div class="page-header">
                      <h1>Save annotations</h1>
                    </div>
                    <p class="lead">Explains how to store annotations locally and upload them to a CMF instance.</p>
          
                    <div class="row-fluid">
                      <h2>Screencast</h2>
                      <object width="790" height="410"><param name="movie" value="https://www.youtube-nocookie.com/v/qmNjs0VxRSQ?hl=de_DE&amp;version=3&amp;rel=0"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://www.youtube-nocookie.com/v/qmNjs0VxRSQ?hl=de_DE&amp;version=3&amp;rel=0" type="application/x-shockwave-flash" width="790" height="410" allowscriptaccess="always" allowfullscreen="true"></embed></object>
                      <h2>Detailed description</h2>
                      <p>There are different ways to store annotation which have been created using the annotation tool.</p>
                      <ul>
                      	<li>Store the annotations locally as RDF/XML, n3 turtle or n3 triples file</li>
                        <li>Save the annotations to a Connected Media Framework instance</li>
                      </ul>
                      <p>If you want to save your annotations in a file, select save from the main menu and choose between the serialization you prefer.</p>
                      <p>If you have finished annotating you can also submit your annotations to a CMF instance by selecting "Save" and click on "Save your annotations to the CMF".</p>
                      <p>You will get response from the annotator if your operation was successful.</p>
                    </div>
                  </section>
                </div>
                
                <div class="span9">
                  <section id="additional">
                    <div class="page-header">
                      <h1>Additional info</h1>
                    </div>
                    <p class="lead">More interesting information about the annotation tool.</p>
          
                    <div class="row-fluid">
                      <h2>Detailed description</h2>
                      <p>Visit our website <a href="http://www.connectme.at/" target="_blank">www.connectme.at</a> to find out more about the annotation tool and the ConnectME project.</p>
                    </div>
                  </section>
                </div>
                
                <div class="clear"></div>
                
              </div> <!-- sxrollspy container -->
        
            </div>
            <div class="footer"></div>
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->
      
      {include
        file="layout/footer.tpl"
        language=$language
      }

    </div><!--/.fluid-container-->

    {include
      file="layout/scripts.tpl"
      language=$language
    }
    
    {literal}
    <script type="text/javascript">
			$(document).ready(function() {
				
				var $scrollingDiv = $("#help-nav-menu");
				
				if ($('body').width() > 766) {
					setScrollingDiv($scrollingDiv);				
				}
				
				$(window).resize(function() {
					if ($('body').width() > 766) {
						setScrollingDiv($scrollingDiv);				
					}
					else {
						// remove scrolling div
						$scrollingDiv.animate({"marginTop": "30px"}, "fast" );
						$(window).unbind("scroll");
					}
				});
				
				// $('#help-nav-menu').scrollspy()
				
				function setScrollingDiv($scrollingDiv) {
					$(window).scroll(function(){			
						$scrollingDiv
							.stop()
							.animate({"marginTop": ($(window).scrollTop() + 30) + "px"}, "slow" );			
					});
				}
				
			});
		</script>
    {/literal}
    
  </body>
  
  {include
  	file="layout/foot.tpl"
  	language=$language
  }